#! /bin/sh

wid=$1
class=$2
instance=$3
consequences=$4

if [[ "$class" == "firefox" && "$instance" == "Toolkit" ]];
then
    eval "$consequences"
    [ "$state" ] || echo "state=floating"
    echo "sticky=on"
fi
