#!/usr/bin/env bash

set -e

if [ "$SPIN" ]; then
    rm ~/.zshrc
    rm ~/.zlogin
    export PATH="$HOME/.nix-profile/bin:$PATH"
    export NIX_PATH="$HOME/.nix-defexpr/channels"
fi

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PREZTO_DIR="${ZDOTDIR:-$HOME}/.zprezto"

if [ ! -d "$PREZTO_DIR" ]; then
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "$PREZTO_DIR"
fi

cd "${BASEDIR}"

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

if [[ "$OSTYPE" == "darwin"* ]]; then
    brew bundle
    type lua-format
    if [ $? != 0 ]; then
        luarocks install --server=https://luarocks.org/dev luaformatter
    fi
fi

type home-manager || {
    echo "Installing home-manager"
    nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
    nix-channel --update
    nix-shell '<home-manager>' -A install
}

if [ "$SPIN" ]; then
    echo "(import ~/dotfiles/nix/spin.nix)" >> ~/.config/nixpkgs/home.nix
else
    echo "(import ~/dotfiles/nix/home.nix)" >> ~/.config/nixpkgs/home.nix
fi

home-manager switch
