#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

function link {
  from=$1
  to=$2

  rm -rf "$to"
  ln -s "$BASEDIR/$from" "$to"
}

mkdir -p ~/.local/bin
mkdir -p ~/.config

link zlogin ~/.zlogin
link zshrc ~/.zshrc
link zpreztorc ~/.zpreztorc
link zprofile ~/.zprofile
link zshenv ~/.zshenv
link kitty ~/.config/kitty
link nvim ~/.config/nvim
link default-gems ~/.default-gems
link tool-versions ~/.tool-versions
link tmux ~/.config/tmux
link rails_test ~/.local/bin/rails_test
link tc-watch ~/.local/bin/tc-watch
link tmux-sessionizer ~/.local/bin/tmux-sessionizer
link validate ~/.local/bin/validate
link wezterm ~/.config/wezterm
link git ~/.config/git

if [[ "$OSTYPE" == "darwin"* ]]; then
  mkdir -p ~/Library/Application Support/Cursor/User/
  link cursor/settings.json ~/Library/Application Support/Cursor/User/settings.json
  link cursor/keybindings.json ~/Library/Application Support/Cursor/User/keybindings.json
fi

if [ "$SPIN" ]; then
  rm -rf ~/.zshrc ~/.zlogin
fi
