#!/bin/bash

set -e

if command -v fd &>/dev/null; then
	test_file=$(fd '.*_test.rb' | fzf)
	watch_files="fd --extension rb"
else
	test_file=$(find . -name '*_test.rb' -printf '%P\n' | fzf)
	watch_files="find . -name "*.rb""
fi

bundle exec rails test "$test_file"
$watch_files | entr -cp bundle exec rails test "$test_file"
