pacman_install rofi
yay_install wlroots
yay_install sway
yay_install swayidle
pacman_install swaylock
pacman_install light
pacman_install waybar
pacman_install otf-font-awesome
pacman_install ttf-font-awesome
pacman_install nautilus
pacman_install mako
