require("key-menu").set("n", "<leader>r", { desc = "Rust", buffer = true })

vim.keymap.set("n", "<leader>rb", function()
  vim.cmd("belowright split term://cargo build")
  vim.cmd("startinsert")
end, { desc = "cargo build", buffer = true })
vim.keymap.set("n", "<leader>rr", function()
  vim.cmd("belowright split term://cargo run")
  vim.cmd("startinsert")
end, { desc = "cargo run", buffer = true })
vim.keymap.set("n", "<leader>rt", function()
  vim.cmd("belowright split term://cargo test")
end, { desc = "cargo test", buffer = true })
