DATA_PATH = vim.fn.stdpath('data')
CACHE_PATH = vim.fn.stdpath('cache')

require('plugins')
require('settings')
require('mappings')
vim.cmd('source ~/.config/nvim/theme.vim')

-- LSP
require('lsp/efm')
require('lsp/lua')
require('lsp/typescript')
require('lsp/python')
require('lsp/yaml')
require('lsp/terraform')
require('lsp/bash')
require('lsp/elm')

-- plugins
require('plugins/lsp-saga')
require('plugins/telescope')
require('plugins/lspkind')
require('plugins/nvim-compe')
require('plugins/better-whitespace')
require('plugins/vim-polyglot')
require('plugins/lspconfig')
require('plugins/lsp-saga')
require('plugins/floaterm')
require('plugins/git-messenger')
require('plugins/git-gutter')
require('plugins/galaxyline')
require('plugins/neogit')
require('plugins/treesitter')
require('plugins/nvim-tree')
require('plugins/vim-rooter')
